from influxdb_client_3.write_client.domain.write_precision_converter import WritePrecisionConverter as WritePrecisionConverter
from influxdb_client_3.write_client.rest import ApiException as ApiException
from influxdb_client_3.write_client.service._base_service import _BaseService

class WriteService(_BaseService):
    def __init__(self, api_client=None) -> None: ...
    def post_write(self, org, bucket, body, **kwargs): ...
    def post_write_with_http_info(self, org, bucket, body, **kwargs): ...
    async def post_write_async(self, org, bucket, body, **kwargs): ...
