import types
from _typeshed import Incomplete
from influxdb_client_3.write_client.client._base import _BaseClient
from influxdb_client_3.write_client.client.write_api import PointSettings as PointSettings, WriteApi as WriteApi, WriteOptions as WriteOptions

logger: Incomplete

class InfluxDBClient(_BaseClient):
    api_client: Incomplete
    def __init__(self, url, token: str = None, debug=None, timeout: int = 10000, enable_gzip: bool = False, org: str = None, default_tags: dict = None, gzip_threshold=None, **kwargs) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: types.TracebackType | None) -> None: ...
    @classmethod
    def from_config_file(cls, config_file: str = 'config.ini', debug=None, enable_gzip: bool = False, **kwargs): ...
    @classmethod
    def from_env_properties(cls, debug=None, enable_gzip: bool = False, **kwargs): ...
    def write_api(self, write_options=..., point_settings=..., **kwargs) -> WriteApi: ...
    def close(self) -> None: ...
    def __del__(self) -> None: ...
