import logging
from _typeshed import Incomplete
from influxdb_client_3.write_client import InfluxDBClient as InfluxDBClient

class InfluxLoggingHandler(logging.Handler):
    DEFAULT_LOG_RECORD_KEYS: Incomplete
    bucket: Incomplete
    client: Incomplete
    write_api: Incomplete
    def __init__(self, *, url, token, org, bucket, client_args=None, write_api_args=None) -> None: ...
    def __del__(self) -> None: ...
    def close(self) -> None: ...
    def emit(self, record: logging.LogRecord) -> None: ...
