from influxdb_client_3.version import USER_AGENT as USER_AGENT
from pyarrow.flight import FlightStreamReader as FlightStreamReader

class QueryApiOptions:
    tls_root_certs: bytes
    tls_verify: bool
    proxy: str
    flight_client_options: dict
    timeout: float
    disable_grpc_compression: bool
    middleware: list
    def __init__(self, root_certs_path: str, verify: bool, proxy: str, flight_client_options: dict, timeout: float = ..., disable_grpc_compression: bool = False, middleware: list = None) -> None: ...

class QueryApiOptionsBuilder:
    def root_certs(self, path: str): ...
    def tls_verify(self, verify: bool): ...
    def proxy(self, proxy: str): ...
    def flight_client_options(self, flight_client_options: dict): ...
    def timeout(self, timeout: float): ...
    def disable_grpc_compression(self, disable: bool): ...
    def middleware(self, middleware: list): ...
    def build(self) -> QueryApiOptions: ...

class QueryApi:
    def __init__(self, connection_string, token, flight_client_options, proxy=None, options=None) -> None: ...
    def query(self, query: str, language: str, mode: str, database: str, **kwargs): ...
    async def query_async(self, query: str, language: str, mode: str, database: str, **kwargs): ...
    def close(self) -> None: ...
