from _typeshed import Incomplete
from influxdb_client_3.write_client import SigninService as SigninService, SignoutService as SignoutService
from influxdb_client_3.write_client._sync import rest as rest
from influxdb_client_3.write_client.configuration import Configuration as Configuration

class ApiClient:
    PRIMITIVE_TYPES: Incomplete
    NATIVE_TYPES_MAPPING: Incomplete
    configuration: Incomplete
    pool_threads: Incomplete
    rest_client: Incomplete
    default_headers: Incomplete
    cookie: Incomplete
    def __init__(self, configuration=None, header_name=None, header_value=None, cookie=None, pool_threads=None, retries: bool = False) -> None: ...
    def __del__(self) -> None: ...
    @property
    def pool(self): ...
    @property
    def user_agent(self): ...
    @user_agent.setter
    def user_agent(self, value) -> None: ...
    def set_default_header(self, header_name, header_value) -> None: ...
    @staticmethod
    def should_gzip(payload: str, enable_gzip: bool = False, gzip_threshold: int = None) -> bool: ...
    def sanitize_for_serialization(self, obj): ...
    def deserialize(self, response, response_type): ...
    def call_api(self, resource_path, method, path_params=None, query_params=None, header_params=None, body=None, post_params=None, files=None, response_type=None, auth_settings=None, async_req=None, _return_http_data_only=None, collection_formats=None, _preload_content: bool = True, _request_timeout=None, urlopen_kw=None): ...
    def request(self, method, url, query_params=None, headers=None, post_params=None, body=None, _preload_content: bool = True, _request_timeout=None, **urlopen_kw): ...
    def parameters_to_tuples(self, params, collection_formats): ...
    def prepare_post_parameters(self, post_params=None, files=None): ...
    def select_header_accept(self, accepts): ...
    def select_header_content_type(self, content_types): ...
    def update_params_for_auth(self, headers, querys, auth_settings) -> None: ...
