import io
from _typeshed import Incomplete
from influxdb_client_3.write_client.rest import ApiException as ApiException

class RESTResponse(io.IOBase):
    urllib3_response: Incomplete
    status: Incomplete
    reason: Incomplete
    data: Incomplete
    def __init__(self, resp) -> None: ...
    def getheaders(self): ...
    def getheader(self, name, default=None): ...

class RESTClientObject:
    configuration: Incomplete
    pools_size: Incomplete
    maxsize: Incomplete
    retries: Incomplete
    pool_manager: Incomplete
    def __init__(self, configuration, pools_size: int = 4, maxsize=None, retries: bool = False) -> None: ...
    def request(self, method, url, query_params=None, headers=None, body=None, post_params=None, _preload_content: bool = True, _request_timeout=None, **urlopen_kw): ...
    def GET(self, url, headers=None, query_params=None, _preload_content: bool = True, _request_timeout=None, **urlopen_kw): ...
    def HEAD(self, url, headers=None, query_params=None, _preload_content: bool = True, _request_timeout=None, **urlopen_kw): ...
    def OPTIONS(self, url, headers=None, query_params=None, post_params=None, body=None, _preload_content: bool = True, _request_timeout=None, **urlopen_kw): ...
    def DELETE(self, url, headers=None, query_params=None, body=None, _preload_content: bool = True, _request_timeout=None, **urlopen_kw): ...
    def POST(self, url, headers=None, query_params=None, post_params=None, body=None, _preload_content: bool = True, _request_timeout=None, **urlopen_kw): ...
    def PUT(self, url, headers=None, query_params=None, post_params=None, body=None, _preload_content: bool = True, _request_timeout=None, **urlopen_kw): ...
    def PATCH(self, url, headers=None, query_params=None, post_params=None, body=None, _preload_content: bool = True, _request_timeout=None, **urlopen_kw): ...
