from _typeshed import Incomplete
from typing import Self
import datetime

from influxdb_client_3.write_client.client.util.date_utils import get_date_helper as get_date_helper
from influxdb_client_3.write_client.domain.write_precision import WritePrecision as WritePrecision

EPOCH: Incomplete
DEFAULT_WRITE_PRECISION: Incomplete

_FieldType = int|float|str|bool|datetime.datetime
_TimeType = datetime.datetime|datetime.timedelta|int|float

class Point:
    _name: str
    _tags: dict[str, str]
    _fields: dict[str, _FieldType]
    _time: _TimeType|None
    @staticmethod
    def measurement(measurement: str): ...
    @staticmethod
    def from_dict(dictionary: dict, write_precision: str = ..., **kwargs): ...
    def __init__(self, measurement_name: str) -> None: ...
    def time(self, time: _TimeType, write_precision: str=...) -> Self: ...
    def tag(self, key: str, value: str) -> Self: ...
    def field(self, field: str, value: _FieldType) -> Self: ...
    def to_line_protocol(self, precision=None, tag_order=None): ...
    @property
    def write_precision(self): ...
    @classmethod
    def set_str_rep(cls, rep_function) -> None: ...

def sanitize_tag_order(tag_order): ...
def ordered_tag_keys(existing_keys, tag_order=None): ...
