from _typeshed import Incomplete
from influxdb_client_3.write_client.client.util.date_utils import get_date_helper as get_date_helper
from influxdb_client_3.write_client.domain.write_precision import WritePrecision as WritePrecision

EPOCH: Incomplete
DEFAULT_WRITE_PRECISION: Incomplete

class Point:
    @staticmethod
    def measurement(measurement): ...
    @staticmethod
    def from_dict(dictionary: dict, write_precision: WritePrecision = ..., **kwargs): ...
    def __init__(self, measurement_name) -> None: ...
    def time(self, time, write_precision=...): ...
    def tag(self, key, value): ...
    def field(self, field, value): ...
    def to_line_protocol(self, precision=None, tag_order=None): ...
    @property
    def write_precision(self): ...
    @classmethod
    def set_str_rep(cls, rep_function) -> None: ...

def sanitize_tag_order(tag_order): ...
def ordered_tag_keys(existing_keys, tag_order=None): ...
