import pandas as pd
import polars as pl
import types
from _typeshed import Incomplete
from influxdb_client_3.write_client import Point as Point, WriteOptions as WriteOptions
from influxdb_client_3.write_client.client.write_api import ASYNCHRONOUS as ASYNCHRONOUS, PointSettings as PointSettings, SYNCHRONOUS as SYNCHRONOUS
from influxdb_client_3.write_client.domain.write_precision import WritePrecision as WritePrecision
from typing import Any, Literal, Iterable

__all__ = ['InfluxDBClient3', 'Point', 'PointSettings', 'SYNCHRONOUS', 'ASYNCHRONOUS', 'WritePrecision', 'WriteOptions', 'write_client_options', 'flight_client_options', 'file_parser_options']

def write_client_options(**kwargs): ...
def flight_client_options(**kwargs): ...
def file_parser_options(**kwargs): ...

class InfluxDBClient3:
    base_url: Incomplete
    default_header: Incomplete
    rest_client: Incomplete

    def __init__(self, host: str|None = None, org: str|None = None, database: str|None = None, token: str|None = None, auth_scheme: object|None = None, enable_gzip: bool = False, gzip_threshold: int|None = None, write_client_options: dict[str, Any]|None = None, flight_client_options: dict[str, Any]|None = None, write_port_overwrite: int|None = None, query_port_overwrite: int|None = None, disable_grpc_compression: bool = False, point_settings: PointSettings|None = None, debug: bool = False, **kwargs) -> None: ...
    @classmethod
    def from_env(cls, **kwargs: Any) -> InfluxDBClient3: ...
    def write(self, record: Iterable[Point]|None=None, database: str|None=None, **kwargs): ...
    def write_dataframe(self, df: pd.DataFrame | pl.DataFrame, measurement: str, timestamp_column: str, tags: list[str] | None = None, timestamp_timezone: str | None = None, database: str | None = None, **kwargs): ...
    def write_file(self, file, measurement_name=None, tag_columns=None, timestamp_column: str = 'time', database=None, file_parser_options=None, **kwargs) -> None: ...
    def query(self, query: str, language: str = 'sql', mode: str = 'all', database: str | None = None, **kwargs): ...
    def query_dataframe(self, query: str, language: str = 'sql', database: str | None = None, frame_type: Literal['pandas', 'polars'] = 'pandas', **kwargs) -> pd.DataFrame | pl.DataFrame: ...
    async def query_async(self, query: str, language: str = 'sql', mode: str = 'all', database: str | None = None, **kwargs): ...
    def get_server_version(self) -> str: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> InfluxDBClient3: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: types.TracebackType | None) -> None: ...
