class UploadFile:
    def __init__(self, file, file_parser_options=None) -> None: ...
    def load_file(self): ...
    def load_feather(self, file): ...
    def load_parquet(self, file): ...
    def load_csv(self, file): ...
    def load_orc(self, file): ...
    def load_json(self, file): ...
