import types
from _typeshed import Incomplete
from influxdb_client_3 import write_client_options as write_client_options
from influxdb_client_3.exceptions import InfluxDBError as InfluxDBError
from influxdb_client_3.write_client import WriteApi as WriteApi, WriteOptions as WriteOptions
from influxdb_client_3.write_client._sync import rest_client as rest_client

logger: Incomplete

class _PoisonPill: ...

class MultiprocessingWriter:
    __started__: bool
    ctx: Incomplete
    on_shutdown: Incomplete
    disposed: Incomplete
    process: Incomplete
    kwargs: Incomplete
    queue_: Incomplete
    def __init__(self, start_method: str = 'spawn', process_ttl: int = 300, on_shutdown=None, **kwargs) -> None: ...
    def write(self, **kwargs) -> None: ...
    def run(self, write_api: WriteApi, disposed, process_ttl, on_shutdown) -> None: ...
    def start(self) -> None: ...
    def get_start_processing_method(self): ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: types.TracebackType | None) -> None: ...
    def __del__(self) -> None: ...
